updated readme with blurb, live url & install notes
Mayden-Academy/2020-sept-maze-game pull request #22
Opened 2021-02-22 23:53 UTC by davin2020

updated readme with blurb, live url & install notes

2021-02-23 10:39 UTC, mporam requested changes

2021-02-23 10:39 UTC, mporam commented on README.md
> +It was designed for a a laptop/desktop with a mouse, rather than a touch screen device
"for a a" ??

2021-02-23 12:08 UTC, davin2020 commented on README.md
> +It was designed for a a laptop/desktop with a mouse, rather than a touch screen device
updated

2021-02-24 10:35 UTC, mporam approved these changes

2021-02-24 10:35 UTC, merged